# The parent image. At build time, this image will be pulled and
# subsequent instructions run against it.
FROM ubuntu:21.10

# Update apt cache and install nginx without an approval prompt.
RUN apt-get update && apt-get install --yes nginx

# Tell Docker this image's containers will use port 80.
EXPOSE 80

# Run Nginx in the foreground. This is important: without a
# foreground process the container will automatically stop.
CMD ["nginx","-g","daemon off;"]
